### ISSUE TITLE
Need an option to disconnect a wallet

### ISSUE THREAD

**Issue by anaelleparity** [Proof-Of-Chaos/website#115]
Hello team,

It would be good to provide an option to disconnect a wallet once it has been connected.

Thanks.

**Comment by niklasp** [comment]
Do you have any example app where thats possible? Already raised an issue in the polkadot extension repo.

I can only imagine storing some flag in localstorage when a user does not automatically want to be reconnected?

**Comment by anaelleparity** [comment]
Hi @niklasp

There are [Singular](https://singular.app/) and [KodaDOT](https://kodadot.xyz/).

Cheers.

**Comment by niklasp** [comment]
I checked the sites. I totally agree with you UX wise. The thing is, those sites do not _really_ disconnect, i.e. disallow the site to read the wallet browser extensions (extensions, accounts). They just store a value in localstorage if wallets should be read from the extension. 

What we really want is that after clicking disconnect, the user has to allow the site again to access the extension
<img width="553" alt="Bildschirmfoto 2023-09-29 um 00 15 01" src="https://github.com/Proof-Of-Chaos/website/assets/1685139/8298c4dd-8dd4-4552-a1e7-289fd80df07e"> 
?

https://github.com/polkadot-js/extension/issues/1288
