### ISSUE TITLE
Past referenda page

### ISSUE THREAD

**Issue by gabrieljaegerde** [Proof-Of-Chaos/website#14]
I am working to get the indexer up asap. Once we are indexing our settings and distribution data, we can display them on the past referenda page on our website.

Per referendum we should display the settings (maybe only the most important ones and the rest on pop-up?), the distribution chart (the ones from the tweets) as well as indicate the vote amount of the user, which NFT they received and their quiz answers.

As for the distribution chart we need to make it more clear but I have an idea of how to do that thanks to an idea by TheFVK on Twitter.

I will update here once the indexer is close to being done so that we can get started on the frontend stuff.

**Comment by niklasp** [comment]
can you post some more info like a static url for each referendum where i can get the chart (would be cool) and the endpoints as soon as they are available.

I think i will go with a tabbed solution on the "Vote" page (like we had at the beginning) default selected is active, but users can switch to "past" and see the data:

- [ ] title
- [ ] id
- [ ] short description
- [ ] outcome
- [ ] user vote amount / conviction
- [ ] distribution chart

?

**Comment by gabrieljaegerde** [comment]
That sounds like a good idea!

Also to include

- [ ] which dragon user had equipped 
- [ ] which nft they received
- [ ] and their answers: score of how many correct shown on main page (i.e. 4/5 correct) and then quiz questions with correct answers and user answers blended it on a pop up)
- [ ] config

all the above assumes a wallet is connected

Distribution chart should probably be on popup as well, same with config (formerly referred to as settings).

**Comment by niklasp** [comment]
Cost estimation (80$ hourly rate)
- ui frame 4-5h (quiz score + answers, config, received nft, referendum info, outcome, vote, ...)
- Distribution graph 2-4h

**Comment by niklasp** [comment]
I need from you @gabrieljaegerde or @tumispro 👍
- [ ] endpoint to get past referenda from indexer / polkadotjs (paginated?, limit by ?)

_Will extend this when i need more_

**Comment by gabrieljaegerde** [comment]
Ok. I will allocate an initial $80 * 6h = $480 with a max. $720 for this task. Please let me know if you go above the 4h for UI Frame and 2h for Distribution graph.

**Comment by niklasp** [comment]
reachted 5h (even more (~3h) for debugging a memory issue which i hope i eliminated in the current version) for the ui frame of past ref. will put the next work into building a popup with the missing information / distribution stats / graphs

**Comment by gabrieljaegerde** [comment]
Looks really great so far:
Some things i noticed as I played around with it:
1. Content does not update when I change wallet.
2. The votes don't seem up to date. It seems that currently we are showing the first vote a user did. Note that votes can be updated/overwritten by voting again.
3. While I did not check the exact probabilities themselves, below the minValue chances at receiving common should 100%.
4. Should we show the common, rare, epic NFTs on the popup along with the NFT the user received?

**Comment by niklasp** [comment]
1 ✅ 
2 ✅ 
3 ✅ 
4 ✅ 
5 ✅

**Comment by gabrieljaegerde** [comment]
Did you double check 3? Or should i check it out?

**Comment by niklasp** [comment]
finished in 9h at ce430d1d3
