### ISSUE TITLE
Take Quiz button should update after a user has submitted a quiz

### ISSUE THREAD

**Issue by niklasp** [Proof-Of-Chaos/website#20]
was working but probably not after code changes to quiz submit logic.

should read from indexer. write  `useQuiz` `useUserQuizzes`

**Comment by niklasp** [comment]
1-1.5h @80$

**Comment by gabrieljaegerde** [comment]
Let me check this out for a sec cuz it was working fine for me before i merged

**Comment by gabrieljaegerde** [comment]
reason why the button is not working is because the answers are not saved in indexer. I am investigating but I think there is a bug in how I write it to the chain.

**Comment by gabrieljaegerde** [comment]
Should be resolved
