### ISSUE TITLE
The identicon showed when connected is not correct

### ISSUE THREAD

**Issue by Tbaut** [Proof-Of-Chaos/website#31]
Hi, when you connect your wallet, the identicon you show is not correct

What you show
![image](https://user-images.githubusercontent.com/33178835/196927500-dcd64a44-e8d9-468e-85a8-b6e21b8d849d.png)
What it should be (this is from pjs extension)
 ![image](https://user-images.githubusercontent.com/33178835/196927557-ce99f049-f414-4b2f-9c84-331447141ac5.png)

There's a handy npm package for this https://www.npmjs.com/package/@polkadot/react-identicon

**Comment by niklasp** [comment]
Thanks for raising an issue. #18
