### ISSUE TITLE
Update UI

### ISSUE THREAD

**Issue by gabrieljaegerde** [Proof-Of-Chaos/website#4]
Update UI to make the quiz and voting standalone features.

The two buttons should be: 1. Take Quiz 2. Vote

Buttons on the quiz modal should let the user know that the answers are written to the chain (maybe "Submit Quiz to Chain).

After taking the quiz and when the answers have been written to the chain successfully, the user gets redirected to the vote modal as is done currently (no changes here). 

A green notification box on the vote modal should let the user know that the answers have been saved to the chain. A yellow box should indicate if the user has voted already (if yes, then what amount + conviction). 

If the user voted already, they should be informed that they can vote again if they would like to overwrite the existing vote but this is not necessary. If the user has not voted yet, they should be encourage to vote as well.

**Comment by niklasp** [comment]
@tumispro @gabrieljaegerde did you already write the `saveQuizAnswersToChan` function? I do not want to break things there

**Comment by niklasp** [comment]
@gabrieljaegerde can this be closed for now?
