### ISSUE TITLE
Check that all needed fields land in ipfs meta correctly

### ISSUE THREAD

**Issue by niklasp** [Proof-Of-Chaos/website#68]
looks like this atm
<img width="705" alt="Bildschirmfoto 2023-07-21 um 17 28 22" src="https://github.com/Proof-Of-Chaos/website/assets/1685139/d9751cb2-54fc-4df3-b7f8-2e1ca41c4968">

**Comment by niklasp** [comment]
artist? what else is missing?

**Comment by niklasp** [comment]
i added `image` recently and expect mimetype must be added too for kodadot? wating for answer from them

**Comment by niklasp** [comment]
according to vikival kodadot sticks to Opensea standard of attributes like so
<img width="468" alt="Bildschirmfoto 2023-07-22 um 00 58 26" src="https://github.com/Proof-Of-Chaos/website/assets/1685139/188fc976-4f11-4c8d-84cf-99d869907045">

**Comment by gabrieljaegerde** [comment]
That is weird. The attributes in nfts pallet are added via the setAttribute call. This has already been fixed on their staging site and should get pushed to their production site soon. See [here](https://github.com/kodadot/nft-gallery/issues/6426#event-9863757937)

**Comment by vikiival** [comment]
> The attributes should not be in the metadata if my understanding is correct.

We support both versions. And frontend shows them all.


whats the metadata standard that has `mediaUri` ? cc @niklasp 



> on their staging site and should get pushed to their production site soon

Available already on https://canary.kodadot.xyz please check

**Comment by niklasp** [comment]
Thanks gor checking back @vikiival. Mediauri was from singular afaik. We'll just go with setAttribute extrinsic.

**Comment by vikiival** [comment]
> Mediauri was from singular afaik.

If `mediaUri` is image in your type I would rather prefer `image`

**Comment by niklasp** [comment]
attributes look good on canary: https://canary.kodadot.xyz/stmn/gallery/34-2, except substrate addresses @vikiival I checked our code and it is most definately a string: "DhvRNnnsyykGpmaa9GMjK9H4DeeQojd5V5qCTWd1GoYwnTc" 
<img width="717" alt="Bildschirmfoto 2023-07-22 um 21 01 26" src="https://github.com/Proof-Of-Chaos/website/assets/1685139/d20db193-6204-4f13-8971-d3722136dae1">
