### ISSUE TITLE
DirectOnly attribute bug

### ISSUE THREAD

**Issue by gabrieljaegerde** [Proof-Of-Chaos/website#76]
DirectOnly attribute in config is not working as intended. When this is set to true, delegated votes should be considered as not meeting requirements.

**Comment by niklasp** [comment]
is this fixed?

**Comment by gabrieljaegerde** [comment]
Not yet. U can take this otherwise I can too.

**Comment by niklasp** [comment]
please can you do it?

**Comment by gabrieljaegerde** [comment]
ok. ill do it.

**Comment by gabrieljaegerde** [comment]
Got deeper into this. Right now all our delegated votes have a `lockedWithDelegation: 0` because it looks like we are [ignoring delegations](https://github.com/Proof-Of-Chaos/website/blob/09d45c67f02a86ed004f05e29a4f274eef2f75a2/src/pages/api/nft_sendout_script/src/_helpersVote.ts#L527) when we calculate the locks. So it doesn't matter if `directOnly` is set to `true` or `false`. Delegated votes are currently always considered to have `lockedWithDelegation: 0` and thus never meet the requirements

**Comment by gabrieljaegerde** [comment]
So it seems like the whole time we were not considering governance locks from delegations. We are now considering those in [9279639](https://github.com/Proof-Of-Chaos/website/commit/9279639b8ebf96eb7b26093e1852b0b71ce8eb8c).
