### ISSUE TITLE
UX improvements

### ISSUE THREAD

**Issue by gabrieljaegerde** [Proof-Of-Chaos/website#78]
Currently the collection selection is a bit confusing. I think we should have only two options/buttons here. Mint into default collection or create new one.

Thoughts?

**Comment by niklasp** [comment]
If a user has a nft collection they want to mint into? I think thats a valid use case

**Comment by gabrieljaegerde** [comment]
I don't think we should allow that. Because then they may have minted other stuff into it before. I think we should also add an extrinsic to lock the collection at the end if the user is minting into a new collection.

**Comment by gabrieljaegerde** [comment]
I realize the user can also mint stuff into their own collection between creation and rewards creation but this way I feel like the UI also becomes easier to understand no?

**Comment by gabrieljaegerde** [comment]
is this done?

**Comment by niklasp** [comment]
check how it is now. users can select any collection to mint to or create a new collection, which will insert the id automatically and render the field disabled in between and display a loading message. I consider it done for now. check it out and close or comment if you want improvements for beta
