### ISSUE TITLE
Authenticity check

### ISSUE THREAD

**Issue by gabrieljaegerde** [Proof-Of-Chaos/website#79]
A way to ensure authenticity of NFTs is by saving all the IDs of all the NFTs minted through our UI to the config of that sendout. Do you think this is a good idea @niklasp ? 

It would be an attribute with a very big array. 

This way we can easily build an authenticity checker as well. And users could easily distinguish between NFTs created through our UI for voters and NFTs minted by the owner of the collection directly (in possible bad faith).

**Comment by niklasp** [comment]
sounds good if you prefer it to indexers with remarks

**Comment by gabrieljaegerde** [comment]
done in [0802601](https://github.com/Proof-Of-Chaos/website/commit/08026012e23a869f26d799ad30aa611ea0d5820c)
