### ISSUE TITLE
Query for all past referenda

### ISSUE THREAD

**Issue by gabrieljaegerde** [Proof-Of-Chaos/website#82]

**Comment by gabrieljaegerde** [comment]
@niklasp we now have a function to query all past refs: [09d45c6](https://github.com/Proof-Of-Chaos/website/commit/09d45c67f02a86ed004f05e29a4f274eef2f75a2)

Can you please help me call it to build the dropdown options.

**Comment by niklasp** [comment]
fixed in beta. please work there for the moment
